apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app: sample-service
spec:
  type: NodePort
  ports:
    - port: 4569
      nodePort: 30080
  selector:
    app: sample-service
